### ISSUE TITLE
Installed but can't use in Git bash win10

### ISSUE THREAD

**Issue by ssghost** [imachug/win-sudo#11] opened 2018-05-03 17:53 UTC
I was successfully installed win-sudo in Git-bash of Win10, but then I typed any command begin with "sudo" a prompt box would pop up and notice me to "execute bash.exe",  I clicked on "yes", and nothing happened after this, the cursor stayed at the next command line (which was empty) of Git bash window.

**Comment by heidricha** [comment] 2018-05-04 08:04
Same for me. sudo command is accepted, win asks for elevated permissions, but nothing else happens, console freeze at this point.
ctrl-c doesn't work, must stop with ctrl-z, and kill %1

**Comment by chimericdream** [comment] 2018-05-04 21:42
Dang. I just came across this myself and was super excited, but I had the same issue as both of you. Here's hoping it might be an easy fix!

**Comment by purplesyringa** [comment] 2018-05-05 12:11
Working on this!

**Comment by purplesyringa** [comment] 2018-05-05 12:39
Does `sudo echo 1` work for you? I've just installed win-sudo via `curl -s https://raw.githubusercontent.com/imachug/win-sudo/master/install.sh | sh` and it works for me.

There was a bug with usernames containing special characters (including space), is this the case for you?

**Comment by ssghost** [comment] 2018-05-08 15:35
I've tried it again. The problem still exists. My username has no special characters.

**Comment by purplesyringa** [comment] 2018-05-08 15:43
Okay, I'll add some debugging output and send you the link soon.

**Comment by purplesyringa** [comment] 2018-05-08 15:52
@ssghost I've pushed to branch `testing`. Please do:

```bash
$ git clone https://github.com/imachug/win-sudo
$ cd win-sudo
$ git checkout testing
$ ./su
```

...and post the output. You should get:

```
going to start sudo
sudo started
checking admin
checking args
checking WSL
backend: /c/Users/Ivanq/Documents/win-sudo/sudobackend
created fifos: /tmp/.sudo.20675
created io fifos
set traps

<UAC window will be opened now>

bash: cannot set terminal process group (3140): Operation not permitted
bash: no job control in this shell

Ivanq@ASUS-PC MSYS ~/Documents/win-sudo (master) [SUDO]
$ started powershell
pid: 1924
set SIGINT trap
passed stdin
passed stdout&stderr

<type 'exit' now>

exit
got: 1
finished
cleaning
cleaning done
```

**Comment by rawhead** [comment] 2018-05-17 13:32
```
./su
going to start sudo
sudo started
checking admin
checking args
checking WSL
backend: /c/Users/jfenk/win-sudo/sudobackend
created fifos: /tmp/.sudo.22528
created io fifos
set traps
started powershell
pid: 6312
set SIGINT trap
passed stdin
passed stdout&stderr
```

The line `res=$(cat "$fifoid.finish")` will cause the problem.
Seems like the finish pipe never closes.

**Comment by purplesyringa** [comment] 2018-05-17 13:44
So, does nothing happen when you type `exit<enter>`?

**Comment by rawhead** [comment] 2018-05-18 05:43
No.

**Comment by purplesyringa** [comment] 2018-05-18 13:26
Try `Ctrl+C`.

**Comment by heidricha** [comment] 2018-05-23 13:03
passed stdin
passed stdout&stderr
exit
< nothing happens, so pressed ctrl-z>
[1]+  Stopped                 ./su

later it can be handled as a normal bash job. fg, bg, kill works.

$ kill %1
cleaning
[1]+  Terminated              ./su

G508031@RMM-P7000032FW MINGW64 ~/Work/win-sudo (testing)
$ cleaning done

**Comment by tulakalbeyo** [comment] 2018-06-07 19:43
i'm having this problem, too. on git's bash. 
![capture](https://user-images.githubusercontent.com/371842/41122443-6fa2443c-6a50-11e8-9e24-df493770c92d.PNG)

**Comment by purplesyringa** [comment] 2018-06-08 05:06
Can you check if Git Bash or Powershell or Command line are running in background while sudo is hanging?

**Comment by RicardoRdzG** [comment] 2018-07-27 01:49
It doesn't work for me either it just hangs and there is no output, in testing branch there is some output  
 ./su
going to start sudo
sudo started
checking admin
checking args
checking WSL
backend: /c/Users/ricardo/bin/win-sudo/s/sudobackend
created fifos: /tmp/.sudo.13739
created io fifos
set traps
started powershell
pid: 27364
set SIGINT trap
passed stdin
passed stdout&stderr

bash is running in the background but it doesn't die even after closing the window you have to kill it from task manager or do C^z and then kill %1

**Comment by RicardoRdzG** [comment] 2018-07-27 07:35
Looks like the problem is in the backend for some reason is not loading the path and can't find cat, just added /bin/ before each cat and it seems to work. Not sure it is the best solution but it works for now

**Comment by purplesyringa** [comment] 2018-08-17 16:23
Looks like the problem was fixed.

**Closed as completed by purplesyringa** 2018-08-17 16:23 UTC
Labels: bug

**Comment by ZenSurfer** [comment] 2020-04-02 02:45
still not working

**Comment by coolerthenU2** [comment] 2020-06-04 17:47
> Does `sudo echo 1` work for you? I've just installed win-sudo via `curl -s https://raw.githubusercontent.com/imachug/win-sudo/master/install.sh | sh` and it works for me.
> 
> There was a bug with usernames containing special characters (including space), is this the case for you?

i have a space in my name, how to do i fix this problem?
